assignment=cipher

$(assignment):
		g++ $(CXXFLAGS) -o $(assignment) *.cpp

tar:
		tar -czf Haselden-Jennifer-PA1.tar.gz *.h *.cpp Makefile

clean:
		rm -f $(assignment) Haselden-Jennifer-PA1.tar.gz *.o *.gch *.gcov a.out